# Generated by Django 3.2.12 on 2022-04-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listbanks',
            fields=[
                ('cod_compensacao', models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Código de Compensação')),
                ('nome_instituicao', models.CharField(max_length=150, verbose_name='Nome da Instituição')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['cod_compensacao'],
            },
        ),
    ]
